#:schema node_modules/wrangler/config-schema.json

name = "atbspb-blog"
compatibility_date = "2026-05-01"

[build]
  command = "pnpm build"
  cwd = "."

[vars]
  NODE_ENV = "production"

[assets]
  directory = "./dist"

[env.production]
  name = "atbspb-blog"